/**
 * Claude sessions tests (sessions-from-transcripts).
 *
 * The panel used to read `sessions-index.json`, a file Claude Code stopped
 * maintaining — on a real machine it held three entries whose transcripts
 * had all been deleted, while fourteen live transcripts sat unlisted in the
 * same directory. These tests pin the replacement: the list comes from the
 * `<sessionId>.jsonl` transcripts, an index file present or not changes
 * nothing, and the title never degrades into harness scaffolding.
 */

const { test, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs');
const os = require('os');
const path = require('path');

const sessions = require('../src/main/claudeSessionsManager');

const PROJECT = '/Users/someone/my.project';
const ENCODED = '-Users-someone-my-project';

let configDir;
let prevConfigDir;

beforeEach(() => {
  configDir = fs.mkdtempSync(path.join(os.tmpdir(), 'frame-claude-'));
  prevConfigDir = process.env.CLAUDE_CONFIG_DIR;
  process.env.CLAUDE_CONFIG_DIR = configDir;
  sessions._resetCache();
});

afterEach(() => {
  if (prevConfigDir === undefined) delete process.env.CLAUDE_CONFIG_DIR;
  else process.env.CLAUDE_CONFIG_DIR = prevConfigDir;
  fs.rmSync(configDir, { recursive: true, force: true });
});

function projectDir() {
  const dir = path.join(configDir, 'projects', ENCODED);
  fs.mkdirSync(dir, { recursive: true });
  return dir;
}

function writeTranscript(sessionId, records) {
  const file = path.join(projectDir(), `${sessionId}.jsonl`);
  fs.writeFileSync(file, records.map(r => JSON.stringify(r)).join('\n') + '\n', 'utf8');
  return file;
}

function userRecord(text, extra = {}) {
  return {
    type: 'user',
    message: { role: 'user', content: text },
    timestamp: '2026-08-01T10:00:00.000Z',
    gitBranch: 'main',
    ...extra
  };
}

function assistantRecord(timestamp = '2026-08-01T10:00:05.000Z') {
  return { type: 'assistant', message: { role: 'assistant', content: 'ok' }, timestamp };
}

test('lists sessions from transcripts, newest activity first', async () => {
  writeTranscript('11111111-1111-4111-8111-111111111111', [
    userRecord('older session', { timestamp: '2026-07-01T09:00:00.000Z' }),
    assistantRecord('2026-07-01T09:00:10.000Z')
  ]);
  writeTranscript('22222222-2222-4222-8222-222222222222', [
    userRecord('newer session', { timestamp: '2026-08-20T09:00:00.000Z' }),
    assistantRecord('2026-08-20T09:30:00.000Z')
  ]);

  const { sessions: list, reason } = await sessions.getSessionsForProject(PROJECT);

  assert.equal(reason, null);
  assert.deepEqual(list.map(s => s.firstPrompt), ['newer session', 'older session']);
  assert.equal(list[0].modified, '2026-08-20T09:30:00.000Z');
  assert.equal(list[0].created, '2026-08-20T09:00:00.000Z');
  assert.equal(list[0].messageCount, 2);
  assert.equal(list[0].gitBranch, 'main');
});

test('a stale sessions-index.json changes nothing', async () => {
  // The exact failure this spec fixes: an index naming a transcript that no
  // longer exists, next to a real one it never heard about.
  fs.writeFileSync(path.join(projectDir(), 'sessions-index.json'), JSON.stringify({
    version: 1,
    entries: [{ sessionId: 'deleted-one', summary: 'Ghost', messageCount: 3 }]
  }), 'utf8');
  writeTranscript('33333333-3333-4333-8333-333333333333', [
    userRecord('real session'), assistantRecord()
  ]);

  const { sessions: list } = await sessions.getSessionsForProject(PROJECT);

  assert.equal(list.length, 1);
  assert.equal(list[0].sessionId, '33333333-3333-4333-8333-333333333333');
});

test('title prefers the session title record, then the first real prompt', async () => {
  writeTranscript('44444444-4444-4444-8444-444444444444', [
    userRecord('what the user typed'),
    { type: 'ai-title', aiTitle: 'A named session' },
    assistantRecord()
  ]);
  writeTranscript('55555555-5555-4555-8555-555555555555', [
    userRecord('untitled but typed'), assistantRecord()
  ]);

  const { sessions: list } = await sessions.getSessionsForProject(PROJECT);
  const byId = Object.fromEntries(list.map(s => [s.sessionId, s]));

  assert.equal(byId['44444444-4444-4444-8444-444444444444'].summary, 'A named session');
  assert.equal(byId['55555555-5555-4555-8555-555555555555'].summary, null);
  assert.equal(byId['55555555-5555-4555-8555-555555555555'].firstPrompt, 'untitled but typed');
});

test('scaffolding is never mistaken for the user\'s first prompt', async () => {
  writeTranscript('66666666-6666-4666-8666-666666666666', [
    userRecord('<command-name>/compact</command-name>'),
    userRecord('Caveat: The messages below were generated by the user while running local commands.'),
    userRecord('injected context', { isMeta: true }),
    { type: 'user', message: { role: 'user', content: [{ type: 'tool_result', content: 'file contents' }] }, timestamp: '2026-08-01T10:00:01.000Z' },
    userRecord([{ type: 'text', text: 'the actual question' }]),
    assistantRecord()
  ]);

  const { sessions: list } = await sessions.getSessionsForProject(PROJECT);

  assert.equal(list[0].firstPrompt, 'the actual question');
});

test('transcripts with no conversation are not listed', async () => {
  writeTranscript('77777777-7777-4777-8777-777777777777', [
    { type: 'mode', mode: 'normal' },
    { type: 'permission-mode', permissionMode: 'default' }
  ]);

  const { sessions: list, reason } = await sessions.getSessionsForProject(PROJECT);

  assert.equal(list.length, 0);
  assert.equal(reason, 'no-project-sessions');
});

test('appended records are picked up on a re-read', async () => {
  const id = '88888888-8888-4888-8888-888888888888';
  const file = writeTranscript(id, [userRecord('first'), assistantRecord()]);

  const before = await sessions.getSessionsForProject(PROJECT);
  assert.equal(before.sessions[0].messageCount, 2);

  fs.appendFileSync(file, JSON.stringify(userRecord('second', {
    timestamp: '2026-08-02T11:00:00.000Z'
  })) + '\n' + JSON.stringify(assistantRecord('2026-08-02T11:00:09.000Z')) + '\n');

  const after = await sessions.getSessionsForProject(PROJECT);
  assert.equal(after.sessions[0].messageCount, 4);
  assert.equal(after.sessions[0].modified, '2026-08-02T11:00:09.000Z');
  // The first prompt is still the first one, not the appended message.
  assert.equal(after.sessions[0].firstPrompt, 'first');
});

test('a rewritten (shrunk) transcript is rescanned from the start', async () => {
  const id = '99999999-9999-4999-8999-999999999999';
  const file = writeTranscript(id, [
    userRecord('long original'), assistantRecord(), assistantRecord('2026-08-01T10:00:07.000Z')
  ]);
  const first = await sessions.getSessionsForProject(PROJECT);
  assert.equal(first.sessions[0].messageCount, 3);

  fs.writeFileSync(file, JSON.stringify(userRecord('rewritten')) + '\n', 'utf8');

  const second = await sessions.getSessionsForProject(PROJECT);
  assert.equal(second.sessions[0].messageCount, 1);
  assert.equal(second.sessions[0].firstPrompt, 'rewritten');
});

test('a truncated trailing line does not lose the rest of the session', async () => {
  const id = 'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
  const file = writeTranscript(id, [userRecord('live session'), assistantRecord()]);
  fs.appendFileSync(file, '{"type":"assistant","mess');

  const { sessions: list } = await sessions.getSessionsForProject(PROJECT);

  assert.equal(list[0].messageCount, 2);
  assert.equal(list[0].firstPrompt, 'live session');
});

test('empty-state reasons stay distinguishable', async () => {
  assert.equal((await sessions.getSessionsForProject(null)).reason, 'no-project');

  // Claude Code has never run here at all.
  process.env.CLAUDE_CONFIG_DIR = path.join(configDir, 'nothing-here');
  assert.equal((await sessions.getSessionsForProject(PROJECT)).reason, 'no-claude-dir');

  // It has, but not for this project.
  process.env.CLAUDE_CONFIG_DIR = configDir;
  fs.mkdirSync(path.join(configDir, 'projects'), { recursive: true });
  assert.equal((await sessions.getSessionsForProject(PROJECT)).reason, 'no-project-sessions');
});

test('project paths containing dots resolve to Claude Code\'s directory name', async () => {
  writeTranscript('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb', [userRecord('dotted path'), assistantRecord()]);

  const { sessions: list } = await sessions.getSessionsForProject(PROJECT);

  assert.equal(list.length, 1, `expected the encoded directory ${ENCODED} to be found`);
});
